/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LangApp2IndexImport } from './routes/$lang/app2/index'
import { Route as LangApp2AboutImport } from './routes/$lang/app2/about'

// Create/Update Routes

const LangApp2IndexRoute = LangApp2IndexImport.update({
  id: '/$lang/app2/',
  path: '/$lang/app2/',
  getParentRoute: () => rootRoute,
} as any)

const LangApp2AboutRoute = LangApp2AboutImport.update({
  id: '/$lang/app2/about',
  path: '/$lang/app2/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang/app2/about': {
      id: '/$lang/app2/about'
      path: '/$lang/app2/about'
      fullPath: '/$lang/app2/about'
      preLoaderRoute: typeof LangApp2AboutImport
      parentRoute: typeof rootRoute
    }
    '/$lang/app2/': {
      id: '/$lang/app2/'
      path: '/$lang/app2'
      fullPath: '/$lang/app2'
      preLoaderRoute: typeof LangApp2IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/$lang/app2/about': typeof LangApp2AboutRoute
  '/$lang/app2': typeof LangApp2IndexRoute
}

export interface FileRoutesByTo {
  '/$lang/app2/about': typeof LangApp2AboutRoute
  '/$lang/app2': typeof LangApp2IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$lang/app2/about': typeof LangApp2AboutRoute
  '/$lang/app2/': typeof LangApp2IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$lang/app2/about' | '/$lang/app2'
  fileRoutesByTo: FileRoutesByTo
  to: '/$lang/app2/about' | '/$lang/app2'
  id: '__root__' | '/$lang/app2/about' | '/$lang/app2/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LangApp2AboutRoute: typeof LangApp2AboutRoute
  LangApp2IndexRoute: typeof LangApp2IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LangApp2AboutRoute: LangApp2AboutRoute,
  LangApp2IndexRoute: LangApp2IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$lang/app2/about",
        "/$lang/app2/"
      ]
    },
    "/$lang/app2/about": {
      "filePath": "$lang/app2/about.tsx"
    },
    "/$lang/app2/": {
      "filePath": "$lang/app2/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
